import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { isMobile } from 'react-device-detect';
import { PdvComponent } from '../../components/PdvComponent'
import Router from 'next/router';
import { PromocaoComponent } from '../../components/PromocaoComponent';
import { EmpresaProvider } from '../../context/empresaContext';
import { AuthProvider } from '../../context';

export default function Pdv() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [sairPdv, setSairPdv] = useState(true);

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute md:relative')
        }
    }, [mobile]);

    useEffect(() => {
        if (localStorage.getItem("applojaweb_token") == null) {
            Router.push('/login');
        }
    });

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | PDV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Header hiddenDrawer={hiddenDrawer} setHiddenDrawer={setHiddenDrawer} />
                <div className='flex-1 min-h-screen sm:flex sm:flex-row '>
                    <Drawer hiddenDrawer={hiddenDrawer} sairPdv={sairPdv} />
                    <div className='flex flex-col items-center sm:w-full '>
                        <PromocaoComponent />
                        <h1 className='font-bold mt-4 text-3xl'>PDV</h1>
                        <PdvComponent setSairPdv={setSairPdv} />
                    </div>
                </div>
            </EmpresaProvider>
        </AuthProvider>
    )
}