import Head from 'next/head'
import { LoginComponent } from '../../components/LoginComponent'

export default function Login() {

    return (
        <div className='bg-gray-200'>
            <Head>
                <title>APPLoja Web | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <LoginComponent />

        </div>
    )
}
