import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { PlanosComponent } from '../../components/PlanosComponent'
import { PromocaoComponent } from '../../components/PromocaoComponent'
import { RenovacaoAlert } from '../../components/RenovacaoAlertComponent';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function Planos() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();
    const [empresa, setEmpresa] = useState({})
    const [planAlert, setPlanAlert] = useState(false)

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Planos</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <RenovacaoAlert empresa={empresa} planAlert={planAlert} setPlanAlert={setPlanAlert} />
                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Planos</h1>
                    <PlanosComponent empresa={empresa} />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}