import Head from "next/head";
import { Header } from "../../../components/Header";
import { Drawer } from "../../../components/Drawer";
import { PromocaoComponent } from "../../../components/PromocaoComponent";
import { NewPdvComponent } from "../../../components/newPdvComponent";
import { useEffect, useState } from "react";
import { isMobile } from "react-device-detect";
import { useRouter } from "next/router";
import { FaGear } from "react-icons/fa6";
import { LoadingComponent } from "../../../components/LoadingComponent";
import { Content } from "../../../components/content";
import { AuthProvider } from "../../../context";
import { EmpresaProvider } from "../../../context/empresaContext";

export default function Pedido() {

    const router = useRouter()

    const { pedido } = router.query


    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [sairPdv, setSairPdv] = useState(true);
    const [empresa, setEmpresa] = useState(null)
    const [config, setConfig] = useState(false)
    const [loading, setLoading] = useState(false)

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute md:relative')
        }
    }, [mobile]);

    useEffect(() => {
        setLoading(true)
        if (pedido) {
            setLoading(false)
        }

    }, [pedido])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Pedido</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <div className='flex flex-row w-full justify-between items-center px-4'>
                        <div className="text-lg font-bold">{pedido ? `Pedido: ${pedido}` : null}</div>
                        <h1 className='font-bold text-3xl'>PDV</h1>
                        <button onClick={() => setConfig(!config)} className='p-4'>
                            <FaGear className='w-7 h-7 text-gray-700' />
                        </button>
                    </div>

                    {loading ? <LoadingComponent /> : <NewPdvComponent empresa={empresa} setSairPdv={setSairPdv} idVenda={pedido} config={config} setConfig={setConfig} />}
                </Content>

            </EmpresaProvider>
        </AuthProvider>
    )
}