import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { PromocaoComponent } from '../../components/PromocaoComponent'
import { DashboardFinanceiro } from '../../components/DashboardFinanceiro';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function DashboardFinanceiroPage() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Financeiro</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Financeiro</h1>
                    <DashboardFinanceiro />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}