import Head from 'next/head'
import { RecuperarSenhaComponent } from '../../components/RecuperarSenhaComponent'

export default function Recuperar() {

    return (
        <>
            <Head>
                <title>APPLoja Web | Recuperar Senha</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <RecuperarSenhaComponent />

        </>
    )
}
