import Head from 'next/head'
import { useState } from 'react'
import ReactGA from 'react-ga4';
import { DashboardComponentNew } from '../../components/DashboardComponentNew';
import { EntradaProdutoModal } from '../../components/EntradaProdutoModal';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

ReactGA.initialize('G-EXCKC833V1');

export default function Home() {


  const [produtoSelecionado, setProdutoSelecionado] = useState();
  const [hiddenEntradaProdutoModal, setHiddenEntradaProdutoModal] = useState('hidden');
  const [atualizarModel, setAtualizarModel] = useState(false);
  const [atualizarListaBaixoEstoque, setAtualizarListaBaixoEstoque] = useState(true);



  return (
    <AuthProvider>
      <EmpresaProvider>
        <Head>
          <title>APPLoja Web</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Content>
          <h1 className='px-5 font-bold mt-4 text-3xl max-h-full'>Dashboard</h1>
          <DashboardComponentNew
            produtoSelecionado={produtoSelecionado}
            setProdutoSelecionado={setProdutoSelecionado}
            hiddenEntradaProdutoModal={hiddenEntradaProdutoModal}
            setHiddenEntradaProdutoModal={setHiddenEntradaProdutoModal}
            atualizarModel={atualizarModel}
            setAtualizarModel={setAtualizarModel}
            atualizarListaBaixoEstoque={atualizarListaBaixoEstoque}
            setAtualizarListaBaixoEstoque={setAtualizarListaBaixoEstoque}
          />
          <EntradaProdutoModal
            produtoSelecionado={produtoSelecionado}
            setProdutoSelecionado={setProdutoSelecionado}
            hiddenEntradaProdutoModal={hiddenEntradaProdutoModal}
            setHiddenEntradaProdutoModal={setHiddenEntradaProdutoModal}
            atualizarModel={atualizarModel}
            setAtualizarModel={setAtualizarModel}
            atualizar={atualizarListaBaixoEstoque}
            setAtualizar={setAtualizarListaBaixoEstoque}
          />
        </Content>

      </EmpresaProvider>
    </AuthProvider>
  )
}