import Head from 'next/head'
import { useState, useEffect } from 'react'; // Aqui você importa o useEffect
import { ConfigNavigationPanel } from '../../components/ConfiguracoesComponente';
import { Header } from "../../components/Header";
import { isMobile } from 'react-device-detect';
import { Drawer } from '../../components/Drawer';
import { PromocaoComponent } from '../../components/PromocaoComponent';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';


export default function ConfigNavigation() {

  const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
  const [mobile, setMobile] = useState()

  useEffect(() => {
    if (isMobile) {
      setHiddenDrawer('hidden')
    } else {
      setHiddenDrawer('absolute md:relative')
    }
  }, [mobile]);

  return (
    <AuthProvider>
      <EmpresaProvider>
        <Head>
          <title>APPLoja Web | Configurações</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Content>
          <h1 className='font-bold mt-4 text-3xl'>Configurações do Sistema</h1>
          <ConfigNavigationPanel />
        </Content>
      </EmpresaProvider>
    </AuthProvider>
  )
}

