import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import Router from 'next/router';
import { Header } from '../../components/Header';
import { Drawer } from '../../components/Drawer';
import { PromocaoComponent } from '../../components/PromocaoComponent';
import { RelatorioComponent } from '../../components/RelatorioComponent';
import { LimiterComponent } from '../../components/LimiterComponent';
import { Content } from '../../components/content';
import { EmpresaProvider } from '../../context/empresaContext';
import { AuthProvider } from '../../context';

export default function Relatorios() {
  const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
  const [mobile, setMobile] = useState()
  const [empresa, setEmpresa] = useState(null)

  useEffect(() => {
    if (isMobile) {
      setHiddenDrawer('hidden')
    } else {
      setHiddenDrawer('absolute lg:relative')
    }
  }, [mobile])

  return (
    <AuthProvider>
      <EmpresaProvider>

        <Head>
          <title>APPLoja Web | Relatórios</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Content>
          <LimiterComponent empresa={empresa}>
            <RelatorioComponent />
          </LimiterComponent>
        </Content>

      </EmpresaProvider>
    </AuthProvider>
  )
}
