import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { MercadoPagoCheckoutModal } from '../../components/MercadoPagoCheckoutModal'
import { PlanosNewComponent } from '../../components/PlanosNewComponent'
import { Content } from '../../components/content';
import { EmpresaProvider } from '../../context/empresaContext';
import { AuthProvider } from '../../context';

export default function PlanosNew() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();
    const [hiddenCheckoutModal, setHiddenCheckoutModal] = useState('hidden');
    const [planoSelecionado, setPlanoSelecionado] = useState();

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute md:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Planos</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Planos</h1>
                    <PlanosNewComponent
                        hiddenCheckoutModal={hiddenCheckoutModal}
                        setHiddenCheckoutModal={setHiddenCheckoutModal}
                        planoSelecionado={planoSelecionado}
                        setPlanoSelecionado={setPlanoSelecionado}
                    />
                    <MercadoPagoCheckoutModal
                        hiddenCheckoutModal={hiddenCheckoutModal}
                        setHiddenCheckoutModal={setHiddenCheckoutModal}
                        planoSelecionado={planoSelecionado}
                        setPlanoSelecionado={setPlanoSelecionado}
                    />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}