import Head from 'next/head'
import { useEffect, useState } from 'react'
import { CustomerModal } from '../../components/CustomerModal'
import { CustomerTable } from '../../components/CustomerTable'
import { isMobile } from 'react-device-detect';
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { PromocaoComponent } from '../../components/PromocaoComponent'
import { PaginationComponent } from '../../components/PaginationComponent'
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function Clientes() {
    const [statusModal, setStatusModal] = useState("hidden");
    const [clienteSelecionado, setClienteSelecionado] = useState(null);
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [atualizar, setAtualizar] = useState(false)

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Clientes</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Clientes</h1>
                    <CustomerTable
                        lastPage={setUltimaPagina}
                        atualPagina={pageAtual}
                        statusModal={statusModal}
                        setStatusModal={setStatusModal}
                        setClienteSelecionado={setClienteSelecionado}
                        clienteSelecionado={clienteSelecionado}
                        setAtualizar={setAtualizar}
                        atualizar={atualizar} />
                    <CustomerModal
                        statusModal={statusModal}
                        setStatusModal={setStatusModal}
                        setClienteSelecionado={setClienteSelecionado}
                        clienteSelecionado={clienteSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <PaginationComponent
                        totalPages={ultimaPagina}
                        paginaAtual={setPageAtual}
                    />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}