import Head from "next/head";
import { useEffect, useState } from "react";
import { isMobile } from "react-device-detect";
import { EntradasTable } from "../../components/entradasTable";
import { XmlImporter } from "../../components/xmlImporterModal";
import { PaginationComponent } from "../../components/PaginationComponent";
import { LimiterComponent } from "../../components/LimiterComponent";
import { Content } from "../../components/content";
import { AuthProvider } from "../../context";
import { EmpresaProvider } from "../../context/empresaContext";

export default function Entradas() {

    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [atualizar, setAtualizar] = useState(true);
    const [statusModal, setStatusModal] = useState("hidden");
    const [entradaSelecionada, setEntradaSelecionada] = useState(null);
    const [mobile, setMobile] = useState();
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [hiddenEntrada, setHiddenEntrada] = useState("hidden");
    const [dataEntrada, setDataEntrada] = useState(null)
    const [empresa, setEmpresa] = useState(null)

    const selecionaPagina = (page) => {
        setPageAtual(page);
    }

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Entradas</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <LimiterComponent empresa={empresa}>
                        <h1 className='font-bold mt-4 text-3xl'>Entradas</h1>
                        <EntradasTable
                            lastPage={totalPaginas}
                            atualPagina={pageAtual}
                            statusModal={statusModal}
                            setStatusModal={setStatusModal}
                            entradaSelecionada={entradaSelecionada}
                            setEntradaSelecionada={setEntradaSelecionada}
                            atualizar={atualizar}
                            setAtualizar={setAtualizar}
                            importar={setHiddenEntrada}
                            newEntrada={setDataEntrada}
                        />
                        <XmlImporter
                            visivel={hiddenEntrada}
                            setvisivel={setHiddenEntrada}
                            newData={dataEntrada} delNewData={setDataEntrada}
                            atualizar={atualizar} setAtualizar={setAtualizar}
                            entradaSelecionada={entradaSelecionada}
                            setEntradaSelecionada={setEntradaSelecionada}
                        />
                        <PaginationComponent
                            totalPages={ultimaPagina}
                            paginaAtual={selecionaPagina}
                        />
                    </LimiterComponent>
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}