import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { ProductModal } from '../../components/ProductModal'
import { ProductTable } from '../../components/ProductTable'
import { ColorModal } from '../../components/ColorModal'
import { TipoProdutoModal } from '../../components/TipoProdutoModal'
import { UnidadeModal } from '../../components/UnidadeModal'
import { OrigemModal } from '../../components/OrigemModal'
import { CstIcmsModal } from '../../components/CstIcmsModal'
import { ColecaoModal } from '../../components/ColecaoModal'
import { MarcaModal } from '../../components/MarcaModal'
import { CategoriaModal } from '../../components/CategoriaModal'
import { TamanhoModal } from '../../components/TamanhoModal'
import { ListaPrecoModal } from '../../components/ListaPrecoModal'
import { isMobile } from 'react-device-detect'
import { SubcategoriaModal } from '../../components/SubcategoriaModal'
import { EntradaProdutoModal } from '../../components/EntradaProdutoModal'
import { PaginationComponent } from '../../components/PaginationComponent'
import { Content } from '../../components/content'
import { AuthProvider } from '../../context'
import { EmpresaProvider } from '../../context/empresaContext'
import { BsFiletypeXlsx } from 'react-icons/bs'

export default function Produtos() {
    const [atualizar, setAtualizar] = useState(false);
    const [atualizarColecao, setAtualizarColecao] = useState(true);
    const [atualizarMarca, setAtualizarMarca] = useState(true);
    const [atualizarCategoria, setAtualizarCategoria] = useState(true);
    const [atualizarColor, setAtualizarColor] = useState(true);
    const [atualizarTamanho, setAtualizarTamanho] = useState(true);
    const [atualizarSubcategoria, setAtualizarSubcategoria] = useState(true);
    const [atualizarModel, setAtualizarModel] = useState(true);
    const [statusModal, setStatusModal] = useState("hidden")
    const [statusColorModal, setStatusColorModal] = useState("hidden")
    const [statusTipoProdutoModal, setStatusTipoProdutoModal] = useState("hidden")
    const [statusUnidadeModal, setStatusUnidadeModal] = useState("hidden")
    const [statusOrigemModal, setStatusOrigemModal] = useState("hidden")
    const [statusCstIcmsModal, setStatusCstIcmsModal] = useState("hidden")
    const [statusColecaoModal, setStatusColecaoModal] = useState("hidden")
    const [statusMarcaModal, setStatusMarcaModal] = useState("hidden")
    const [statusCategoriaModal, setStatusCategoriaModal] = useState("hidden")
    const [statusTamanhoModal, setStatusTamanhoModal] = useState("hidden")
    const [statusListaPrecoModal, setStatusListaPrecoModal] = useState("hidden")
    const [statusSubcategoriaModal, setStatusSubcategoriaModal] = useState("hidden")
    const [categoriaId, setCategoriaId] = useState()
    const [produtoSelecionado, setProdutoSelecionado] = useState(null)
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [hiddenEntradaProdutoModal, setHiddenEntradaProdutoModal] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [logado, setLogado] = useState(false);
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);

    const selecionaPagina = (page) => {
        setPageAtual(page);
    }

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Produtos</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Produtos</h1>
                    <ProductTable
                        lastPage={totalPaginas}
                        atualPagina={pageAtual}
                        statusModal={statusModal}
                        setStatusModal={setStatusModal}
                        produtoSelecionado={produtoSelecionado}
                        setProdutoSelecionado={setProdutoSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                        atualizarModel={atualizarModel}
                        setAtualizarModel={setAtualizarModel}
                        hiddenEntradaProdutoModal={hiddenEntradaProdutoModal}
                        setHiddenEntradaProdutoModal={setHiddenEntradaProdutoModal}
                    />
                    <ProductModal
                        produtoSelecionado={produtoSelecionado}
                        setProdutoSelecionado={setProdutoSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                        atualizarColecao={atualizarColecao}
                        setAtualizarColecao={setAtualizarColecao}
                        atualizarMarca={atualizarMarca}
                        setAtualizarMarca={setAtualizarMarca}
                        atualizarCategoria={atualizarCategoria}
                        setAtualizarCategoria={setAtualizarCategoria}
                        atualizarColor={atualizarColor}
                        setAtualizarColor={setAtualizarColor}
                        atualizarTamanho={atualizarTamanho}
                        setAtualizarTamanho={setAtualizarTamanho}
                        atualizarSubcategoria={atualizarSubcategoria}
                        setAtualizarSubcategoria={setAtualizarSubcategoria}
                        atualizarModel={atualizarModel}
                        setAtualizarModel={setAtualizarModel}
                        statusModal={statusModal}
                        setStatusModal={setStatusModal}
                        statusColorModal={statusColorModal}
                        setStatusColorModal={setStatusColorModal}
                        statusTipoProdutoModal={statusTipoProdutoModal}
                        setStatusTipoProdutoModal={setStatusTipoProdutoModal}
                        statusUnidadeModal={statusUnidadeModal}
                        setStatusUnidadeModal={setStatusUnidadeModal}
                        statusOrigemModal={statusOrigemModal}
                        setStatusOrigemModal={setStatusOrigemModal}
                        statusCstIcmsModal={statusCstIcmsModal}
                        setStatusCstIcmsModal={setStatusCstIcmsModal}
                        statusColecaoModal={statusColecaoModal}
                        setStatusColecaoModal={setStatusColecaoModal}
                        statusMarcaModal={statusMarcaModal}
                        setStatusMarcaModal={setStatusMarcaModal}
                        statusCategoriaModal={statusCategoriaModal}
                        setStatusCategoriaModal={setStatusCategoriaModal}
                        statusTamanhoModal={statusTamanhoModal}
                        setStatusTamanhoModal={setStatusTamanhoModal}
                        statusListaPrecoModal={statusListaPrecoModal}
                        setStatusListaPrecoModal={setStatusListaPrecoModal}
                        statusSubcategoriaModal={statusSubcategoriaModal}
                        setStatusSubcategoriaModal={setStatusSubcategoriaModal}
                        setCategoriaId={setCategoriaId}
                    />
                    <ColorModal statusModal={statusColorModal} setStatusModal={setStatusColorModal} atualizar={atualizarColor} setAtualizar={setAtualizarColor} />
                    <TipoProdutoModal statusModal={statusTipoProdutoModal} setStatusModal={setStatusTipoProdutoModal} atualizar={atualizar} setAtualizar={setAtualizar} />
                    <UnidadeModal statusModal={statusUnidadeModal} setStatusModal={setStatusUnidadeModal} atualizar={atualizar} setAtualizar={setAtualizar} />
                    <OrigemModal statusModal={statusOrigemModal} setStatusModal={setStatusOrigemModal} atualizar={atualizar} setAtualizar={setAtualizar} />
                    <CstIcmsModal statusModal={statusCstIcmsModal} setStatusModal={setStatusCstIcmsModal} atualizar={atualizar} setAtualizar={setAtualizar} />
                    <ColecaoModal statusModal={statusColecaoModal} setStatusModal={setStatusColecaoModal} atualizar={atualizarColecao} setAtualizar={setAtualizarColecao} />
                    <MarcaModal statusModal={statusMarcaModal} setStatusModal={setStatusMarcaModal} atualizar={atualizarMarca} setAtualizar={setAtualizarMarca} />
                    <CategoriaModal statusModal={statusCategoriaModal} setStatusModal={setStatusCategoriaModal} atualizar={atualizarCategoria} setAtualizar={setAtualizarCategoria} />
                    <TamanhoModal statusModal={statusTamanhoModal} setStatusModal={setStatusTamanhoModal} atualizar={atualizarTamanho} setAtualizar={setAtualizarTamanho} />
                    <ListaPrecoModal statusModal={statusListaPrecoModal} setStatusModal={setStatusListaPrecoModal} atualizar={atualizar} setAtualizar={setAtualizar} />
                    <SubcategoriaModal statusModal={statusSubcategoriaModal} setStatusModal={setStatusSubcategoriaModal} atualizar={atualizarSubcategoria} setAtualizar={setAtualizarSubcategoria} categoriaId={categoriaId} />
                    <EntradaProdutoModal
                        produtoSelecionado={produtoSelecionado}
                        setProdutoSelecionado={setProdutoSelecionado}
                        hiddenEntradaProdutoModal={hiddenEntradaProdutoModal}
                        setHiddenEntradaProdutoModal={setHiddenEntradaProdutoModal}
                        atualizarModel={atualizarModel}
                        setAtualizarModel={setAtualizarModel}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <PaginationComponent totalPages={ultimaPagina} paginaAtual={selecionaPagina} />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}