import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Drawer } from '../../components/Drawer'
import { Header } from '../../components/Header'
import { isMobile } from 'react-device-detect'
import { VendaTable } from '../../components/VendaTable'
import { PromocaoComponent } from '../../components/PromocaoComponent'
import { PaginationComponent } from '../../components/PaginationComponent'
import { Content } from '../../components/content'
import { AuthProvider } from '../../context'
import { EmpresaProvider } from '../../context/empresaContext'

export default function Pedidos() {
    const [vendaSelecionado, setVendaSelecionado] = useState({});
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [atualizar, setAtualizar] = useState(false)

    const selecionaPagina = (page) => {
        setPageAtual(page);
    }

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Pedidos</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Pedidos</h1>
                    <VendaTable
                        lastPage={totalPaginas}
                        atualPagina={pageAtual}
                        vendaSelecionado={vendaSelecionado}
                        setVendaSelecionado={setVendaSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <PaginationComponent
                        totalPages={ultimaPagina}
                        paginaAtual={selecionaPagina}
                    />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}