import Head from "next/head"
import { Header } from "../../components/Header"
import { useEffect, useState } from "react";
import { Drawer } from "../../components/Drawer";
import { PromocaoComponent } from "../../components/PromocaoComponent";
import { isMobile } from "react-device-detect";
import { Content } from "../../components/content";
import { AuthProvider } from "../../context";
import { EmpresaProvider } from "../../context/empresaContext";

export default function Compras() {

    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');

    const [mobile, setMobile] = useState();

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Compras</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header hiddenDrawer={hiddenDrawer} setHiddenDrawer={setHiddenDrawer} />

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Compras</h1>
                </Content>

            </EmpresaProvider>
        </AuthProvider>
    )
}