import Head from "next/head";
import { useEffect, useState } from "react";
import { Drawer } from "../../components/Drawer";
import { Header } from "../../components/Header";
import { isMobile } from "react-device-detect";
import Router from "next/router";
import { PromocaoComponent } from "../../components/PromocaoComponent";
import { ContasReceberModal } from "../../components/ContasReceberModal";
import { ContasReceberTable } from "../../components/ContasReceberTable";
import { PaginationComponent } from "../../components/PaginationComponent";
import { Content } from "../../components/content";
import { AuthProvider } from "../../context";
import { EmpresaProvider } from "../../context/empresaContext";

export default function ContasReceber() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [hiddenContasReceberModal, setHiddenContasReceberModal] = useState('hidden')
    const [contaReceberSelecionado, setContaReceberSelecionado] = useState({})
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [atualizar, setAtualizar] = useState(false)


    const selecionaPagina = (page) => {
        setPageAtual(page);
    }

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Contas à Receber</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Contas à Receber</h1>
                    <ContasReceberTable
                        lastPage={totalPaginas}
                        atualPagina={pageAtual}
                        setHiddenContasReceberModal={setHiddenContasReceberModal}
                        hiddenContasReceberModal={hiddenContasReceberModal}
                        contaReceberSelecionado={contaReceberSelecionado}
                        setContaReceberSelecionado={setContaReceberSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <ContasReceberModal
                        setHiddenContasReceberModal={setHiddenContasReceberModal}
                        hiddenContasReceberModal={hiddenContasReceberModal}
                        contaReceberSelecionado={contaReceberSelecionado}
                        setContaReceberSelecionado={setContaReceberSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <PaginationComponent totalPages={ultimaPagina} paginaAtual={selecionaPagina} />
                </Content>

            </EmpresaProvider>
        </AuthProvider>
    );
}
