import Head from 'next/head'
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';
import { IndicacoesComponent } from '../../components/indicacoesComponent';

export default function Indicacoes() {

  return (
    <AuthProvider>
      <EmpresaProvider>
        <Head>
          <title>APPLoja Web</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Content>
          <IndicacoesComponent />
        </Content>
      </EmpresaProvider>
    </AuthProvider>
  )
}