import Head from 'next/head';
import { useEffect, useState } from 'react';
import Router, { useRouter } from 'next/router';
import { AiOutlineLoading } from 'react-icons/ai';
import { FaRegSadTear } from 'react-icons/fa';
import { motion } from 'framer-motion';

const PaymentFailurePage = () => {
  const [countdown, setCountdown] = useState(5);
  const transitionDuration = 0.5; // Duração da transição em segundos

  useEffect(() => {
    // Redirecionar para outra página após 5 segundos
    const redirectTimer = setInterval(() => {
      setCountdown((prevCountdown) => prevCountdown - 1);
    }, 1000);

    // Redirecionar após o contador chegar a 1
    if (countdown === 0) {
      Router.push('/');
    }

    // Limpar o timer ao desmontar o componente
    return () => clearInterval(redirectTimer);
  }, [countdown]);

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100">
      <Head>
        <title>APPLoja Web | Pagamento Reprovado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        initial={{ opacity: 0, scale: 0.5 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: transitionDuration }}
        className="bg-white shadow-lg p-8 rounded-lg flex flex-col items-center"
      >
        <motion.div
          initial={{ y: -50, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: transitionDuration, delay: 0.2 }}
        >
          <FaRegSadTear className="text-6xl text-red-500 mb-4" />
        </motion.div>
        <motion.h1
          initial={{ y: -20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: transitionDuration, delay: 0.4 }}
          className="text-4xl font-bold text-center"
        >
          Pagamento Reprovado!
        </motion.h1>
        <motion.p
          initial={{ y: -20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: transitionDuration, delay: 0.6 }}
          className="my-4 text-center"
        >
          O seu pagamento foi reprovado.
        </motion.p>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: transitionDuration, delay: 0.8 }}
        >
          <AiOutlineLoading className="text-4xl animate-spin" />
        </motion.div>
        <motion.p
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: transitionDuration, delay: 1 }}
          className="text-2xl mt-4"
        >
          Redirecionando em {countdown} segundos...
        </motion.p>
      </motion.div>
    </div>
  );
};

export default PaymentFailurePage;
