import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { Header } from '../../components/Header';
import { Drawer } from '../../components/Drawer';
import { PromocaoComponent } from '../../components/PromocaoComponent';
import { VendedorTable } from '../../components/vendedorTableComponent';
import { VendedorModal } from '../../components/vendedorModalComponent';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function Vendedores() {

    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [hiddenUserModal, setHiddenUserModal] = useState('hidden')
    const [vendedorSelecionado, setVendedorSelecionado] = useState(null);
    const [atualizar, setAtualizar] = useState(false)
    const [mobile, setMobile] = useState()

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Vendedores</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Vendedores</h1>
                    <VendedorTable
                        hiddenUserModal={hiddenUserModal}
                        setHiddenUserModal={setHiddenUserModal}
                        vendedorSelecionado={vendedorSelecionado}
                        setVendedorSelecionado={setVendedorSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <VendedorModal
                        hiddenUserModal={hiddenUserModal}
                        setHiddenUserModal={setHiddenUserModal}
                        vendedorSelecionado={vendedorSelecionado}
                        setVendedorSelecionado={setVendedorSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}