import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Header } from '../../../components/Header'
import { Drawer } from '../../../components/Drawer'
import { isMobile } from 'react-device-detect';
import { PagamentoComponent } from '../../../components/PagamentoComponent'
import Router from 'next/router';
import { EmpresaProvider } from '../../../context/empresaContext';
import { AuthProvider } from '../../../context';

export default function Pdv() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute md:relative')
        }
    }, [mobile])

    useEffect(() => {
        if (localStorage.getItem("applojaweb_token") == null) {
            Router.push('/login');
        }
    })

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | PDV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Header hiddenDrawer={hiddenDrawer} setHiddenDrawer={setHiddenDrawer} />
                <div className='min-h-screen sm:flex sm:flex-row '>
                    <Drawer hiddenDrawer={hiddenDrawer} sairPdv={true} />
                    <div className='mx-5 pt-5 flex flex-col items-center sm:w-full '>
                        <h1 className='font-bold text-3xl mb-4'>Pagamento</h1>
                        <PagamentoComponent />
                    </div>
                </div>
            </EmpresaProvider>
        </AuthProvider>
    )
}