import Head from "next/head";
import { useEffect, useState } from "react";
import { isMobile } from "react-device-detect";
import { ContasPagarTable } from "../../components/ContasPagarTable";
import { ContasPagarModal } from "../../components/ContasPagarModal";
import { PaginationComponent } from "../../components/PaginationComponent";
import { Content } from "../../components/content";
import { AuthProvider } from "../../context";
import { EmpresaProvider } from "../../context/empresaContext";

export default function ContasPagar() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [hiddenContasPagarModal, setHiddenContasPagarModal] = useState('hidden')
    const [contaPagarSelecionado, setContaPagarSelecionado] = useState({})
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [atualizar, setAtualizar] = useState(false)

    const selecionaPagina = (page) => {
        setPageAtual(page);
    }

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Contas à pagar</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <h1 className='font-bold mt-4 text-3xl'>Contas à Pagar</h1>
                    <ContasPagarTable
                        lastPage={totalPaginas}
                        atualPagina={pageAtual}
                        setHiddenContasPagarModal={setHiddenContasPagarModal}
                        hiddenContasPagarModal={hiddenContasPagarModal}
                        contaPagarSelecionado={contaPagarSelecionado}
                        setContaPagarSelecionado={setContaPagarSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <ContasPagarModal
                        setHiddenContasPagarModal={setHiddenContasPagarModal}
                        hiddenContasPagarModal={hiddenContasPagarModal}
                        contaPagarSelecionado={contaPagarSelecionado}
                        setContaPagarSelecionado={setContaPagarSelecionado}
                        atualizar={atualizar}
                        setAtualizar={setAtualizar}
                    />
                    <PaginationComponent
                        totalPages={ultimaPagina}
                        paginaAtual={selecionaPagina}
                    />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    );
};
