import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { NewPdvComponent } from '../../components/newPdvComponent';
import { FaGear } from 'react-icons/fa6';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function Pdv() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
    const [mobile, setMobile] = useState()
    const [sairPdv, setSairPdv] = useState(true);
    const [empresa, setEmpresa] = useState(null)
    const [config, setConfig] = useState(false)

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile]);

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | PDV</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <div className='flex flex-row w-full justify-between items-center'>
                        <div></div>
                        <h1 className='font-bold text-3xl'>PDV</h1>
                        <button onClick={() => setConfig(!config)} className='p-4'>
                            <FaGear className='w-7 h-7 text-gray-700' />
                        </button>
                    </div>
                    {/* <PdvComponent setSairPdv={setSairPdv} /> */}
                    <NewPdvComponent empresa={empresa} setSairPdv={setSairPdv} config={config} setConfig={setConfig} />
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}