import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { EmpresaComponent } from '../../components/EmpresaComponent';
import { Content } from '../../components/content';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function Empresa() {

  const [hiddenDrawer, setHiddenDrawer] = useState('hidden')
  const [mobile, setMobile] = useState()

  useEffect(() => {
    if (isMobile) {
      setHiddenDrawer('hidden')
    } else {
      setHiddenDrawer('absolute lg:relative')
    }
  }, [mobile])

  return (
    <AuthProvider>
      <EmpresaProvider>
        <Head>
          <title>APPLoja Web | Empresa</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Content>
          <h1 className='font-bold mt-4 text-3xl'>Empresa</h1>
          <EmpresaComponent />
        </Content>
      </EmpresaProvider>
    </AuthProvider>
  )
}
