import Head from "next/head";
import { useEffect, useState } from "react";
import { isMobile } from "react-device-detect";
import { PaginationComponent } from "../../components/PaginationComponent";
import { CaixaTable } from "../../components/caixaTable";
import { CaixaModal } from "../../components/caixaModal";
import { LimiterComponent } from "../../components/LimiterComponent";
import { Content } from "../../components/content";
import { AuthProvider } from "../../context";
import { EmpresaProvider } from "../../context/empresaContext";

export default function Caixa() {
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();
    const [ultimaPagina, setUltimaPagina] = useState(1);
    const [pageAtual, setPageAtual] = useState(1);
    const [caixaModalHidden, setCaixaModalHidden] = useState('hidden')
    const [data, setData] = useState(null)
    const [update, setUpdate] = useState(false)

    const totalPaginas = (page) => {
        setUltimaPagina(page)
    }

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Caixa</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <LimiterComponent>
                        <h1 className='font-bold mt-4 text-3xl'>Caixa</h1>
                        <CaixaTable newcaixa={setCaixaModalHidden} ultimapagina={totalPaginas} atualPagina={pageAtual} data={setData} setupdate={setUpdate} update={update} />
                        <PaginationComponent totalPages={ultimaPagina} paginaAtual={setPageAtual} />
                        <CaixaModal visible={caixaModalHidden} setvisible={setCaixaModalHidden} data={data} setData={setData} setupdate={setUpdate} />
                    </LimiterComponent>
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}