import Head from 'next/head'
import { useEffect, useState } from 'react'
import { isMobile } from 'react-device-detect';
import { NotaFiscalTable } from '../../components/NotaFiscalTable'
import { NotaFiscalModal } from '../../components/NotaFiscalModal'
import { PaginationComponent } from '../../components/PaginationComponent'
import { LimiterComponent } from '../../components/LimiterComponent';
import { Content } from '../../components/content';
import { BsFileEarmarkText, BsList } from 'react-icons/bs';
import { RelatorioNfe } from '../../components/relatorioNfeComponent';
import { PopUpCancelaNota } from '../../components/popUpCancelaNotaComponent';
import { AuthProvider } from '../../context';
import { EmpresaProvider } from '../../context/empresaContext';

export default function EmissaoNfe() {
    const [statusModal, setStatusModal] = useState("hidden");
    const [notaFiscalSelecionado, setNotaFiscalSelecionado] = useState({});
    const [hiddenDrawer, setHiddenDrawer] = useState('hidden');
    const [mobile, setMobile] = useState();
    const [ultimaPagina, setUltimaPagina] = useState();
    const [pageAtual, setPageAtual] = useState(1);
    const [empresa, setEmpresa] = useState(null)
    const [reload, setReload] = useState(false)
    const [guiaAberta, setGuiaAberta] = useState('lista-notas')
    const [notaParaCancelar, setNotaParaCancelar] = useState(null)
    const [popUpCancelarNota, setPopUpCancelarNota] = useState(false)

    useEffect(() => {
        if (isMobile) {
            setHiddenDrawer('hidden')
        } else {
            setHiddenDrawer('absolute lg:relative')
        }
    }, [mobile])

    return (
        <AuthProvider>
            <EmpresaProvider>
                <Head>
                    <title>APPLoja Web | Emissão Nota Fiscal</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Content>
                    <LimiterComponent empresa={empresa}>
                        <h1 className='font-bold mt-4 text-3xl'>Emissão Nota Fiscal</h1>
                        <div className='flex flex-row w-4/5 items-center gap-4 max-w-screen-xl py-4'>
                            <button onClick={() => setGuiaAberta('lista-notas')} className='bg-gray-200 px-4 py-3 md:py-1 rounded-lg'>
                                <BsList className='w-10 h-10' />
                            </button>
                            <button onClick={() => setGuiaAberta('relatorio')} className='bg-gray-200 px-4 py-3 md:py-1 rounded-lg'>
                                <BsFileEarmarkText className='w-10 h-10' />
                            </button>
                        </div>
                        <div className={`relative flex flex-col w-full h-full items-center ${guiaAberta === 'lista-notas' ? '' : 'hidden'}`}>
                            <NotaFiscalTable
                                lastPage={setUltimaPagina}
                                atualPagina={pageAtual}
                                notaFiscalSelecionado={notaFiscalSelecionado}
                                setNotaFiscalSelecionado={setNotaFiscalSelecionado}
                                statusModal={statusModal}
                                setStatusModal={setStatusModal}
                                reload={reload}
                                setReload={setReload}
                                popUpCancelarNota={popUpCancelarNota}
                                setPopUpCancelarNota={setPopUpCancelarNota}
                                notaParaCancelar={notaParaCancelar}
                                setNotaParaCancelar={setNotaParaCancelar}
                            />
                            <NotaFiscalModal
                                notaFiscalSelecionado={notaFiscalSelecionado}
                                setNotaFiscalSelecionado={setNotaFiscalSelecionado}
                                statusModal={statusModal}
                                setStatusModal={setStatusModal}
                                reload={reload}
                                setReload={setReload}
                            />
                            <PaginationComponent totalPages={ultimaPagina} paginaAtual={setPageAtual} />
                        </div>
                        <div className={`flex flex-col w-full h-full items-center ${guiaAberta === 'relatorio' ? '' : 'hidden'}`}>
                            <RelatorioNfe />
                        </div>
                        <PopUpCancelaNota
                            popUpCancelarNota={popUpCancelarNota}
                            setPopUpCancelarNota={setPopUpCancelarNota}
                            notaParaCancelar={notaParaCancelar}
                            setNotaParaCancelar={setNotaParaCancelar}
                            reload={reload}
                            setReload={setReload}
                        />
                    </LimiterComponent>
                </Content>
            </EmpresaProvider>
        </AuthProvider>
    )
}